image: mrcyjanek/waydroid:debian-stable 
matrix:
 - env: DISTRO=debian-stable 
   image: mrcyjanek/waydroid:debian-stable 
 - env: DISTRO=debian-unstable
   image: mrcyjanek/waydroid:debian-unstable
 - env: DISTRO=ubuntu-devel
   image: mrcyjanek/waydroid:ubuntu-devel
 - env: DISTRO=ubuntu-latest
   image: mrcyjanek/waydroid:ubuntu-latest
 - env: DISTRO=ubuntu-rolling
   image: mrcyjanek/waydroid:ubuntu-rolling
script:
 - apt update
 - build_changelog
 - mk-build-deps -ir -t "apt-get -o Debug::pkgProblemResolver=yes -y --no-install-recommends"
 - debuild -b -uc -us
 - mkdir -p /apt/$DISTRO/ || true
 - mv ../*.deb /apt/$DISTRO/
