image: mrcyjanek/waydroid:ubuntu-devel
matrix:
 - env: DISTRO=ubuntu-devel
   image: mrcyjanek/waydroid:ubuntu-devel
 - env: DISTRO=sid
   image: mrcyjanek/waydroid:sid
 - env: DISTRO=bookworm
   image: mrcyjanek/waydroid:bookworm
 - env: DISTRO=bullseye
   image: mrcyjanek/waydroid:bullseye
 - env: DISTRO=jammy
   image: mrcyjanek/waydroid:jammy
 - env: DISTRO=focal
   image: mrcyjanek/waydroid:focal
script:
 - apt update
 - build_changelog
 - mk-build-deps -ir -t "apt-get -o Debug::pkgProblemResolver=yes -y --no-install-recommends"
 - debuild -b -uc -us
 - mkdir -p /apt/$DISTRO/ || true
 - mv ../*.deb /apt/$DISTRO/
